<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ControleDeWebServices</RootNamespace>
    <AssemblyName>ControleDeWebServices</AssemblyName>
    <ApplicationIcon>agt_web.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.6" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="PeanutButter.INI" Version="3.0.384" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Comum.Utilitarios">
      <HintPath>Dll\Comum.Utilitarios.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Configuracoes.config" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Configuracoes .config" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="SeloDigital.GO.Servico.dll.config" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Dll\Comum.Utilitarios.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Imagens\*.svg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
