//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeWebServices.Modelo
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Clientes")]
    public partial class Cliente
    {
        [Key]
        [Required(ErrorMessage = "O campo ID não pode ser nulo")]
        [Display(Name = "IdCliente")]
        public int IdCliente { get; set; }
        public int CodigoControle { get; set; }
        [MaxLength(50)]
        public string NomeCliente { get; set; }
        [MaxLength(2)]
        public string Uf { get; set; }
        public List<ClienteSistemas> IdClientesSistema { get; set; }
        [ForeignKey("IdCliente")]
        public List<ClienteServicos> IdClientesServicos { get; set; }
    }
}
